### PR TITLE
[WIP] Adding fr_FR.UTF-8 to the locale generation list

### PR DESCRIPTION
**Pull request by LuisAlejandro**
This corrects the warning described in #16.

Closes vauxoo/docker-ubuntu-base#16
Closes vauxoo/docker-odoo-image#118

### CODE REVIEW

**Comment by moylop260** [comment]
@ruiztulio 
Please, could review this pr?

**Comment by LuisAlejandro** [comment]
@ruiztulio @moylop260 wait, this is still a WIP, there are some errors.

**Comment by ruiztulio** [comment]
@LuisAlejandro You can add the **[WIP]** in the PR name so we know that we cannot merge it or we test it knowing it is a WIP and some errors will appear

**Comment by LuisAlejandro** [comment]
@ruiztulio now is ready for review.

**Comment by LuisAlejandro** [comment]
@ruiztulio there are some missing build dependencies on odoo-shippable, Travis is red.

**Comment by ruiztulio** [comment]
@LuisAlejandro I'm going to include all the build deps in the [odoo image](https://github.com/Vauxoo/docker-odoo-image) to avoid this in the future, I'm having this issues in my local environment too

**Comment by LuisAlejandro** [comment]
@ruiztulio Cool

**Comment by moylop260** [comment]
@ruiztulio 
I don't understand your last message.
The question is: Could you merge it?

**Comment by ruiztulio** [comment]
@moylop260 I tested this. had to build the ubuntu base -> odoo80 -> shippable image then executed the tests with t2d and only found this:

es_pa

But none retaled with fr and the one mentioned [here](https://github.com/Vauxoo/instance/issues/272#issuecomment-220631045)

**Comment by LuisAlejandro** [comment]
@moylop260 @ruiztulio is seems that es_PA is also needed, is there any other one that need to be added?

**Pull request merged**
